### ISSUE TITLE
Toolbar and tree-view node job creation entry points are missing

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1050]
Using the latest bits of the extension, I'm unable to see the toolbar (flask) and tree-view (experiment node) job creation entry points:

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/f76d1c96-97e1-4370-a2d7-0363ee54476a)

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/7256d6ce-b787-4c0d-8689-d2e77671c957)

**Comment by shsuman** [comment]
@SiddhanthUnnithan, Was the Create Job supposed to be in the Experiment tree nodes and not the experiment root tree node. Because as mentioned in #989, "Experiment: Remove "Create Experiment" and standardize on "Create Job" > quick pick.", I thought it was supposed to replace Create Experiment which was present in Experiment root tree node

**Comment by SiddhanthUnnithan** [comment]
Change scope to only cover missing flask icon in the toolbar.

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2247690
