### ISSUE TITLE
Don't need authority in the remote file uri to open a file in remote

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1060]
We don't need this to open a file: vscode-remote://${authority}/${filePath}. 
Only doing this suffice: vscode-remote://amext/${filePath}

Bringing this up because I remember that this full authority caused some problem in the past or was it the other way round ?

**Comment by SiddhanthUnnithan** [comment]
Confirmed that authority was causing problems because of encoding.

Authority is different from URI.

This is not for starting the remote connection. This is for opening the Notebook file that the user passed.

@shsuman tested the new approach for opening Notebook and text documents. Confirmed that it worked.

Follow-up: check with Rob from VS Code to see what the expectation is for file opening.
