### ISSUE TITLE
Investigate schema loading issue.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1067]
Understand why our extension is unable to load the schema, regardless of whether it is specified with the CDN, original blob, or #yaml-language-server comment.

Understand why the RH extension is able to retrieve the schema correctly.

Create an artifact / issue with a breakdown of the failure and how we might be able to resolve this for internal teams and customers.

**Comment by tbombach** [comment]
I am able to repro this now - my cache had a correct version of the schema so our code didn't show any validation errors. When I removed the code that returns schemas from the cache, I could see the issue

![Screen Shot 2021-06-30 at 10.33.38 AM.png](https://images.zenhubusercontent.com/5cdb0d100f84751dcd8fd498/f6c03e25-82a3-4931-9192-24758648c0a3)

**Comment by tbombach** [comment]
I believe this has to do with how node-request-light (which is the same library that red hat extension uses) handles gzip files, plus our cache. Gzip unzip seems to have a problem when trying to unzip the files and throws an error that the file ended unexpectedly. I suspect it works sometimes (and when it does, it gets put in the cache), which is why it works for some users and for the red hat extension. However, our cache seems to get filled with bad paths sometimes (possibly from using the remote extension), so users who get in a bad state stay broken.

**Comment by tbombach** [comment]
I'm building a VSIX that we can test with a change that should address this by avoiding gzip. I'll then tackle our cache issue, but this should make it work more reliably
