### ISSUE TITLE
Make sure that we're logging at the right level to prevent from constantly switching back to Output tab.

### ISSUE THREAD

**Issue by ezwiefel** [microsoft/vscode-tools-for-ai#1073]
## Expected Behavior
When I'm connected to a CI and working in the terminal in VSCode, I expect the terminal to maintain focus on visibility.

## Actual Behavior
When I'm connected to a CI and working in the terminal in VSCode, the screen will frequently change to the "Azure ML - Remote" Output screen to display a URL for the CI
![image](https://user-images.githubusercontent.com/8908818/120340450-ab16c080-c2bb-11eb-86cc-430bc36881b3.png)

This can happen in the middle of typing a command for the terminal window.

## Steps to Reproduce the Problem

  1. Connect to CI via VSCode
  1. Use Terminal
  1. Wait for it to happen at random

## Specifications

  - VS Code Version: 1.56.2
  - AML Extension Version: 0.6.23
  - AML Remote Extension Version: 0.3.0
  - Platform: Mac OS

**Comment by SiddhanthUnnithan** [comment]
@ezwiefel thanks for bringing this up! With more verbose logging turned on, there's not much we as an extension can do. The movement from any tab to Output is VS Code-driven. What we can do on the extension side is be aware of what we're outputting to try and avoid constantly moving to the Output tab.

**Comment by SiddhanthUnnithan** [comment]
Changing the scope of this issue to move some of the current info-level logging to debug so that users are not constantly moved from the Terminal to Output tab.

**Comment by ezwiefel** [comment]
Thanks, @SiddhanthUnnithan!

Are you aware of a setting that can be changed in VSCode to prevent this?

**Comment by SiddhanthUnnithan** [comment]
@ezwiefel I'm unaware of a VS Code setting to prevent this from happening. I think in the meantime we can change the level at which we log our output. For example, the logging for "VS Code Url" should be at the debug level so that we don't pull you back to the Output tab each time the connection is refreshed (or an error occurs).

**Comment by sevillal** [comment]
@SiddhanthUnnithan the switch to the Output window is something the extension is doing and can be avoided.

I think we should do one of the following:
1. Completely remove the switch when logging to output window. 
2. Only switch in case of an error log. 

Personally I am more inclined to 1, since errors should be shown in the notification popups and then we can guide the user to get more details from the output window.
