### ISSUE TITLE
[OCV] Jupyter kernel set to wrong path when opening Notebook in Remote

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1078]
[OCV - Item (microsoft.com) -](https://ocv.microsoft.com/#/item/fdcl_v4_8b8edd1ef8bd56598b86ebbd6855c4c6/)
When I start VS Code as editor application from Computing Instance tab , then open an existing notebook, the current path is not the directory the notebook is stored in.
i.e. the value of print(os.getcwd()) is "/mnt/batch/tasks/shared/LS_root/mounts/clusters/<instancename>/code"

**Comment by SiddhanthUnnithan** [comment]
This may be because the user was connected to VS Code remote and from there was trying to connect to a remote server. The remote server connection will use the Jupyter server at the root of the CI (cloudfiles/code).

Keeping this issue for now and tracking whether other customers are experiencing. Follow up with these customers to see if they're using "Connect to Remote Jupyter Server" after connecting to Remote CI.

**Comment by SiddhanthUnnithan** [comment]
We haven't seen any other occurrences of an incorrect kernel being set. For now we can assume the user was trying to connect to a remote jupyter server from the remote window which is why the kernel was fixed at the root (cloudfiles/code) as opposed to the sub-folder. Closing for now but will reopen if this issue keeps arising.
