### ISSUE TITLE
Clicking out from the Studio doesn't work if Azure ML and VS Code accounts are different

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1159]
[Step 1]
Validate that the remote experience doesn't work if the user is signed into different accounts in the Azure ML Studio vs. through the Azure Account in VS Code. We expect this to fail because the authentication credentials we fetch from the Azure account extension won't work for the compute instance being connected to.

[Step 2]
Display an error message that the compute instance being connected to cannot be accessed by the current user. We won't know the account information in the Studio but we should be able to convey something like "The user <az_account> does not have permissions to connect to the compute <compute_id>. Please ensure that you're signed into the right Azure account and connecting to the right compute instance."

[Step 3]
Tweak the URI parameters to accept authentication credentials (e.g., starting Bearer token) and use this credential to automatically sign into the right account in VS Code. If the user is already signed into an Azure account then attempt to establish the connection with the new credentials. We will need to investigate the feasibility of this approach.

**Comment by tbombach** [comment]
We can get the subscription id from the compute id that the studio sends us. It seems like the best we could do is compare the expected subscription id with the subscriptions available to the user in the extension and show a message/stop trying to connect in that case.

**Comment by SiddhanthUnnithan** [comment]
"The user <az_account> may not have permissions to connect to the compute <compute_id>. Please ensure that you're signed into the right Azure account and connecting to the right compute instance."

We should use an unfiltered list of subscriptions returned by the Azure account when performing the subscription check.

**Comment by sevillal** [comment]
@tbombach @SiddhanthUnnithan adding need triage to this issue since it was brough up in the Usability Studies. 

### How to repro:
- Open vscode login with my sevillal account
- From browser launch the vscode uri to connect to a compute instance in the same subscription but from another user (i.e. one of Sid's CIs)
- Azure ML std extension will launch and will open remote which will fail with 403 error

### Proposed solution
- Before opening remote window validate that the CI can be used (with our canIUse function)
- We've seen failures on the canIUse function in the past, if that still persist we can also add something in the remote extension. If the number of intents to connect to Jupyter endpoint that failed with 403 forbidden is > than some threshold, then show a prompt to the user with a message to make sure is logged in with the right account.

**Comment by tbombach** [comment]
caniuse will need to check multiple things - right now it checks if the user actually has permissions to use the CI. We also would like to check that the subscription exists from what Azure account extension lists, whether the compute id is valid.

We will need to have different errors based on why the user can't use the compute. If the subscription isn't valid (based on the account the user is logged in with), we'll want to prompt them to log in with the different account.
