### ISSUE TITLE
Don't lose comments in default local.runconfig when modifying python path and userManagedDependencies.

### ISSUE THREAD

**Issue by greazer** [Microsoft/vscode-tools-for-ai#117]

**Comment by greazer** [comment]
I'm not sure of the best way to handle this. The reason we're losing comments on updating a runconfig file is due to the way the yml library works that I used to update it. We could just change the way we modify this file to do simple text replacement rather than reading in as yml. I suppose that would be fine, unless there's another library we can use that doesn't lose comments. Considering the fact that yaml supports comments (by design and unlike json), this may exist somewhere.

**Comment by shsuman** [comment]
Well, after digging a lot into it, I have come to the conclusion that retaining comments is not possible using the yml library. Most of the posts suggest that it is better to lose comments instead of using something else. However, there is a way to retain comments using the ruamel.yaml package in python but again that is in python

**Comment by greazer** [comment]
The Azure AML team is scheduled to replace the RunConfig yml file with a json format. The json format will be provided with a schema that can be used to replace the functionality of the comments.
