### ISSUE TITLE
Refactor on WebRequest methods

### ISSUE THREAD

**Issue by LittleLittleCloud** [microsoft/vscode-tools-for-ai#118]
change all WebRequest methods to return an error code (or error instance) instead of either throw or block the errors

**Comment by greazer** [comment]
I spoke with Jake (our new teammember) about this situation since he has a lot of experience with typescript and vscode extensions. He offered a 3rd way of solving this problem and that is through making more use of Promises. Feel free to reach out to him (Jake Radzikowski) with to get his opinion on what would be the best way to handle this particular situation based on these comments and his experience. I'm sure I won't have time.

**Comment by shsuman** [comment]
I think we already propagate errors to the calling function now. Closing this as this is a very old issue
