### ISSUE TITLE
Setting the default workspace in a new remote window

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1181]
1. Should we just propagate what we have in the global storage locally ?
2. Or, set the default workspace in which the remote compute instance lies ?

**Comment by SiddhanthUnnithan** [comment]
Scenario:

User opens folder 1 without a workspace set.

User sets workspace as X.

Extension writes X to global and workspace state.

User opens folder 2 without a workspace set.

Extension automatically sets X as workspace state.

Extension shows toast notification: "The Azure ML extension set the default workspace to X." + Option to Switch.

User sets workspace as Y in folder 2.

Extension writes Y to global and folder 2 workspace state.

User reloads folder 1 but folder 1 workspace is still X (because of workspace state).

User opens folder 3 without a workspace set.

Extension automatically sets Y as workspace state.

**Comment by SiddhanthUnnithan** [comment]
Plan artifact here: https://microsoft.sharepoint.com/:w:/t/python/EUsvNSZZyjdFm4RLkKp1l0UB7C_xB4vaNcbtQow8MCt0VQ?e=1PA6GK

**Comment by shsuman** [comment]
https://github.com/microsoft/vscode-azureml/pull/11
