### ISSUE TITLE
[Triage] When debugging on remote CI file with breakpoints is opened twice pointing to different locations

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#1205]
VS Code version: 1.58.2
Azure ML Ext version: 0.6.24
Azure ML Remote version: 0.4.0

User workflow:
- Start CI from ML Studio
- Open VS Code
- Connect to CI
- Open a python file from the file explorer
- Set breakpoints and start debugging
- After some time (user reported ~2 hours of idle time) when breakpoint is reached it opens a second file that points to the same one but with the mnt path

I.e. 
Original file open: /home/azureuser/cloudfiles/code/src/myfile.py
Second file open: /mnt/batch/tasks/shared/LS_root/mounts/clusters/<ci_mount_id>/code/src/myfile.py

Debug configuration used:
 {

            "name": "train",

            "type": "python",

            "request": "launch",

            "program": "<some_file>.py",

            "console": "integratedTerminal"

        }

Note: After this condition is reached opening files from file explorer opens the /mnt/.. path

**Comment by shsuman** [comment]
Initial investigations indicate that this is a generic problem on Linux machines when debugging a python symlink file.

Further investigations to solidify this would be testing in a Windows and Linux container in a VSCode remote window. Also, try debugging other languages in similar scenario

**Comment by shsuman** [comment]
Further investigations showed that this is general problem in VSCode. Even while debugging javascript files which are in a symlinked folder, the same issue occurs. As mentioned in this (issue)[https://github.com/microsoft/vscode/issues/57954], you need to use { "runtimeArgs": ["--preserve-symlinks", "--preserve-symlinks-main"] option in your launch config. Although, this fixes the issue for Windows but does not have any effect on Linux. I have opened an (issue)[https://github.com/microsoft/vscode/issues/130091] against VSCode for the same.

**Comment by shsuman** [comment]
So, apparently this issue cannot be fixed because of OS level restrictions.

 From VSCode:
"I looked into this previously, and unfortunately I don't think it's possible to fix since this is a behavior of the OS microsoft/vscode-js-debug#776 (comment). A workaround you can do is set the "cwd": "/", which does change module resolution behavior subtly but may be sufficient for your needs."

I think if the customer wants to use a specific file name in the "program" field of his/her launch config, the workaround is this:
`{
   "cwd": "/",
   "program": "[absolute-path-to-python-file]"
}`

else `"program": "${file}"` works as expected

**Comment by shsuman** [comment]
Workaround worked for customer.
