### ISSUE TITLE
Follow up with VS Code about extension APIs being available in the remote resolver.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#1209]

**Comment by shsuman** [comment]
I think this issue is not longer valid because we were betting on the fact that Azure Account can be changed to a [workspace, ui] extension. However, as mentioned in this [comment](https://github.com/microsoft/vscode/issues/128573#issuecomment-903514847), this has unforeseen consequences and should be avoided. It also suggests that our remote extension should be [ui] kind instead of [workspace, ui].

Given this new development, I don't think we will be able to convince Azure Account team to switch to [ui] extension instead of [workspace]
