### ISSUE TITLE
[Triage] Local unsaved work lost because of lapse in connection to Compute Instance

### ISSUE THREAD

**Issue by MathieuBeaudoin** [microsoft/vscode-tools-for-ai#1278]
## Expected Behavior
Not suddenly losing all your work, both locally and remotely, because of a temporary lapse in your connection to the Compute Instance.

## Actual Behavior
In the middle of a session, the editor was suddenly unable to connect to the remote Compute Instance. A prompt appeared, saying I needed to reload the window; all my work disappeared. When I reloaded, the file that appeared was the last saved version, rather than the version with the changes I had made since then. I have not found any option to restore my work.

## Specifications

  - Version: 1.60.1
  - Platform: Windows 10

**Comment by sevillal** [comment]
Hi @MathieuBeaudoin! Thanks for filing this. I have some questions about the issue:

1. What version of "Azure Machine Learning" and "Azure Machine Learning - Remote" extensions you have installed?
2. Have you seen the issue more than once?
3. Does the issue happen while the VS Code instance is idle or while you are actively working on it?

Our apologies for the inconvenience, we'll try to get to the bottom of it and fix it.

**Comment by shsuman** [comment]
@MathieuBeaudoin, Just to add one more thing:
 1. Did you have Auto Save enabled in VSCode ?

**Comment by MathieuBeaudoin** [comment]
> 
> 
> Hi @MathieuBeaudoin! Thanks for filing this. I have some questions about the issue:
> 
>     1. What version of "Azure Machine Learning" and "Azure Machine Learning - Remote" extensions you have installed?
> 
>     2. Have you seen the issue more than once?
> 
>     3. Does the issue happen while the VS Code instance is idle or while you are actively working on it?
> 
> 
> Our apologies for the inconvenience, we'll try to get to the bottom of it and fix it.

1) Azure Machine Learning v0.6.25; Azure Machine Learning - Remote v0.4.0
2) It has only happened once
3) I don't recall if I was working on the Notebook at that exact moment or if I had come back to it from doing something else

**Comment by shsuman** [comment]
Hey @MathieuBeaudoin,

Thanks for all the info. Did VSCode not retry to reconnect itself before prompting the reload ?

So, when the connection drops for a short period of time, the extension is configured so that VSCode can auto connect. You will see something like this:

![image](https://user-images.githubusercontent.com/44413557/135251144-4f14d18d-bdce-49c1-b7cb-33979ec0d0f8.png)

The Reload prompt is only shown when the auto reconnection fails or the connection is completely dead. Did you see a prompt like this ?

![image](https://user-images.githubusercontent.com/44413557/135251522-21f07896-1432-4724-91e5-8af7c36c6453.png)

One thing that I can't understand that why didn't VSCode auto saved your work. That is possible if your connection dropped even before you saw the reload prompt. Did you recall anything like that ?

**Comment by MathieuBeaudoin** [comment]
@shsuman I do recall seeing this "Cannot reconnect. Please reload the window." prompt. I did not notice how long my connection to the server had been gone, but I lost several hours' worth of work, and had no problem browsing the web in the meantime so I know it wasn't my internet connection (at least, no more than for a short amount of time before losing my work).

**Comment by shsuman** [comment]
Hey @MathieuBeaudoin,

Thanks for the info. Its quite weird that VSCode did not prompt you to reload and let you work in a disconnected state. However, I am glad that you didn't encounter it again. Please let me know if you are able to repro this, so that I can investigate further.

I will be be closing this for now. Please reopen it if need be.
