### ISSUE TITLE
[Triage] Error: "Cannot read property 'length' of nul" when VS code create ML workspace from YML file.

### ISSUE THREAD

**Issue by HaoHoo** [microsoft/vscode-tools-for-ai#1370]
## Expected Behavior
Create ML workspace by YML file refer by docs:
https://docs.microsoft.com/en-us/azure/machine-learning/reference-yaml-workspace  

## Actual Behavior
VS code extension shows error:  "Cannot read property 'length' of null"

## Steps to Reproduce the Problem

  1. Create YAML from command plate or just copy from docs site.
  2. Right click editor and select "Azure ML: Execute YAML".
  3. Few seconds then VS Code pop the error:  'Cannot read property 'length' of null"

## Specifications

  - Version: Extension v0.6.27 / Azure CLI v2.30 / Azure CLI Extension v2.0.2
  - Platform: Windows v10.0.19043  / VS code v1.62.1

**Comment by HaoHoo** [comment]
Windows now have the same situation as MacOS.
The YAML file can work by “Azure ML: Execute YAML" is because I click  "Set Default Azure ML Workspace" and select an existed AML workspace. And then I can create new one...It not make sense...

**Comment by tbombach** [comment]
Thank you for filing this issue @HaoHoo! I think there are two separate issues here:
- We don't properly quote file paths, which causes an issue for paths with spaces (I created an issue to fix this here: https://github.com/microsoft/vscode-tools-for-ai/issues/1391)
- We currently treat "Create Workspace" similarly to other resources (like Environment or Computes), which use the default workspace for information about the subscription and resource group. As you mention, this doesn't make much sense since a new workspace is unrelated to the Default Workspace. I've created an issue for improving that experience: https://github.com/microsoft/vscode-tools-for-ai/issues/1393

I'm going to close this issue - please follow the two above issues for updates on each individual fix. Thank you!
