### ISSUE TITLE
Remote connection back-end investigation

### ISSUE THREAD

**Issue by tbombach** [microsoft/vscode-tools-for-ai#1379]
We would like to determine the technical challenges for integrating with the service. More information at this issue: https://github.com/microsoft/vscode-azureml/issues/18

**Comment by sevillal** [comment]
Basis known limitations:
1. Not working on old CI's, might be because libssl missing. Needs investigation. 
2. Need a better approach to get the endpoint once the tunnel is hosted in the remote (Basis team has an issue to track)
3. Need to add event to notify when the client is connected, our workaround is to sleep for some time after client connect (Basis team has an issue to track)
4. No auto-shutdown, Jason mentioned adding a capability on the CLI to auto-shutdown once there is no connections open. 
5. TS sdk does not support hosting a tunnel

**Comment by sevillal** [comment]
Please refer to upstream for details on this investigation.
