### ISSUE TITLE
Build Fault tolerant globals (E.g. Logger, Telemetry Service)

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#1407]

**Comment by tbombach** [comment]
Since the extension can run without logger, telemetry, etc. we would like to continue if there's an error initializing these globals. In those cases, we would like to log some telemetry event that indicates this state, but put mock/dummy instances in the global state to allow the extension to continue.

**Comment by shsuman** [comment]
We haven't really seen any case where telemetry or loggers failed to initialize. So, I don't really think that this is necessary.
