### ISSUE TITLE
Cannot retrieve Experiments 

### ISSUE THREAD

**Issue by michalmiki** [microsoft/vscode-tools-for-ai#1507]
Does this occur consistently? YES
Repro steps:

1. Open Visual Studio Code
2. Click on AzureML tab
3. Click on Experiments 

Action: getChildren
Error type: TypeError
Error Message: Cannot read property 'userObjectId' of null

Version: 0.6.28
OS: darwin
OS Release: 21.4.0
Product: Visual Studio Code
Product Version: 1.65.2
Language: en

<details>
<summary>Call Stack</summary>

```
runIndexEntityToRun extension.js:2:4149814
h.<anonymous> extension.js:2:4148788
a extension.js:2:4147753
processTicksAndRejections task_queues.js:93:5

Cannot drill down Experiments anymore, everything else including Compute Instances, Environments etc. works just fine except for Experiments tab. 
```

</details>

**Comment by shsuman** [comment]
Hey, @michalmiki We are in the middle of some major breaking changes. This should be fixed in our next release 0.7.0. For the meantime, can you please switch to an older version of the extension to see if that works. To install a previous version, you can follow the instructions [here](https://code.visualstudio.com/updates/v1_30#_install-previous-versions)

**Comment by shsuman** [comment]
@michalmiki Can you please confirm that if the above workaround worked for you ?

**Comment by shsuman** [comment]
Closing this as we haven't received a response in over 7 days. Please reopen if need be
