### ISSUE TITLE
report

### ISSUE THREAD

**Issue by boscoez** [microsoft/vscode-tools-for-ai#1583]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml.editorTitle.executeYaml
Error type: r
Error Message: The YAML file does not contain a "$schema" tag or "yaml-language-server" comment. Please update the file before creating the resource.

Version: 0.10.0
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.67.2
Language: en

<details>
<summary>Call Stack</summary>

```
H.<anonymous> extension.js:2:2741780
s extension.js:2:2740757
```

</details>

**Comment by sevillal** [comment]
Hi @boscoez, thank you for reporting this and my apologies for the issue you are facing, we will work on solving it.

I have couple of questions about the error, what type of resource are you trying to create? how did you build the YAML file (manually or using the Azure ML Extension)? how does the YAML file you are trying to execute look?

**Comment by boscoez** [comment]
I am only trying to deploy an app for a Computer Science CS446 group project. I designed the template web app iGuide and although not required I am wanting to deploy it live for the instructors to see. I created the pipeline in the azure portal and linked it to git, however it is concurrently "the program" that is is also in the azure cloud and the git repository here.  If that makes sense.  Clearly, I am new to this side of development. haha

**Comment by boscoez** [comment]
html, css, javascript, and bootstrap5 lib i think that is all i have as resources. but remember i placed all the program files in Azure and my git repo maybe not the greatest idea but what is done is done...

**Comment by sevillal** [comment]
@boscoez thanks for the details. I believe our extension needs to remove the button to report an issue since it is misleading here, also disable the editor button if the user is not in the context of an Azure ML yaml file. I have create an issue for that here: https://github.com/microsoft/vscode-tools-for-ai/issues/1588

Unfortunately the editor button you are trying out will not help deploying the application, but we will make sure to improve it to avoid any confusion in the future.

I would suggest you to check out these [tutorials](https://code.visualstudio.com/docs/azure/deployment#_deployment-tutorials) on how to deploy applications from VS Code. 

Please let us know if any help is needed.
