### ISSUE TITLE
The YAML file does not contain a "$schema" tag or "yaml-language-server" comment. Please update the file before creating the resource.

### ISSUE THREAD

**Issue by santcugatonline** [microsoft/vscode-tools-for-ai#1590]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureml.editorTitle.executeYaml
Error type: r
Error Message: The YAML file does not contain a "$schema" tag or "yaml-language-server" comment. Please update the file before creating the resource.

Version: 0.12.0
OS: darwin
OS Release: 18.7.0
Product: Visual Studio Code
Product Version: 1.68.0
Language: es

<details>
<summary>Call Stack</summary>

```
H.<anonymous> extension.js:2:2759200
s extension.js:2:2758177
```

</details>

**Comment by shsuman** [comment]
@santcugatonline You need to provide a schema field in the Yaml file so that we can execute the yaml to create the specified resource.

You can put a $schema field on top like this, you can use Ctrl + Space (Cmd + Space on Mac) to trigger completions for the schema.
![image](https://user-images.githubusercontent.com/44413557/173050721-ec98dddf-8d6a-4563-bf95-70803feb3062.png)
![image](https://user-images.githubusercontent.com/44413557/173050793-405cf9a0-fac9-4441-9e7f-5d8de03a5822.png)
![image](https://user-images.githubusercontent.com/44413557/173050838-b5445e21-735d-4cda-9bb1-eae47938ead3.png)
