### ISSUE TITLE
Avoid prompting for Azure sign-in during activation and rely on log-in UI in tree view

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-tools-for-ai#1606]
- Have the extension installed, along with the Jupyter extensions
- Create a new Jupyter notebook

<img width="647" alt="image" src="https://user-images.githubusercontent.com/323878/177656182-0650de78-3ab1-4119-a19b-678d20dd20e7.png">

Also it seems to show the dialog twice, I have to click cancel twice

**Comment by tbombach** [comment]
Hey Rob, thanks for reporting this. At one point we added a prompt to our extension activation to encourage users to sign in instead of waiting for them to have a degraded experience (for example, we rely on them signing in before we can provide meaningful completions or diagnostics for YAML files). However, I've seen cases like this where the user has to deal with this before they do something completely unrelated in VS Code. @SiddhanthUnnithan - I think we should revisit our experience here. Perhaps we could have a more prominent sign in prompt in the YAML files without having to do this modal prompt. I think it's more expected that Azure extensions wait for the user to sign in without a prompt

**Comment by tbombach** [comment]
Merged PR for this: https://github.com/microsoft/vscode-azureml/pull/323
