### ISSUE TITLE
Install/Upgrade Azure ML Extension runtime dependencies does not complete

### ISSUE THREAD

**Issue by lokinfey** [Microsoft/vscode-tools-for-ai#172]
Ubuntu 18.04.2
VS Code 1.31.1
Azure Machine Learning 0.42
Azure ML SDK 1.0.15
error: Please wait while we install/upgrade the Azure ML extension runtime dependencies

I know that https://github.com/Microsoft/vscode-tools-for-ai/issues/120

But it only fix 0.41,but when 0.42 can not run again

**Comment by shsuman** [comment]
Please do not install the sdk the on your own, since you have already installed 1.0.15 and we do not support 1.0.15, so the extension tries to downgrade the sdk and do some other stuff for it to run. The recommended practice now is to just install the extension and wait for the dependencies to install/upgrade.  The error is because you are trying to force a process in the middle of extension dependencies installation/update.

**Comment by greazer** [comment]
@lokinfey, Shantnu is correct. The architecture is that the extension installs a "hidden", specific version of the SDK in order to do the operations it supports. You, as a user, need to install a separate version of the SDK that will be used by your ML scripts. This version can be whatever version you choose, but is typically the latest version available. So for example, the extension may be using 1.0.2, while your scripts are using 1.0.15.
