### ISSUE TITLE
Selecting default AzureML workspace doesn't ask for resource group

### ISSUE THREAD

**Issue by fschlz** [microsoft/vscode-tools-for-ai#2042]
I've got some AzureML workspaces, that have the same name.
So, I cannot select any of them, b/c I cannot see which ones which.
(The sidebar shows it, once I selected one, but then I'd have to iterate all of them to find the correct one. And that doesn't guarantee that the sorting in the workspace selector doesn't change.)

## Expected Behavior

click bottom bar "Azure ML Workspace: xxx"
in top center selector pops up where you choose the subscription
then select resource group (from this the plugin should be able to figure out itself which Azure Workspace it is)

## Actual Behavior

click bottom bar "Azure ML Workspace: xxx"
in top center selector pops up where you choose the subscription
then you immediately choose the AzureML workspace 👈 broken b/c of above reason
instead, the flow should look like this:

## Specifications

  - Version: v0.32.2
  - Platform: macOS
  - Screen Reader:

**Comment by shsuman** [comment]
@fschlz Although, we won't be able to add the extra resource group step in between the subscription and workspace because we want to minimize the number of steps that a user has to encounter when setting the default workspace. This is also the behavior of the Azure ML Studio. However, I have created a PR to show the resource group name in the description along side the workspace name in the quick picks. That way, you would be able to differentiate between your workspaces easily. Once the Or is merged, the issue will be closed automatically and then after one to two business days, the changes should reflect in our pre release version. Please update the extension to use pre release version by following the steps [here](https://github.com/microsoft/vscode-tools-for-ai/wiki/FAQ#how-to-install-pre-release-version-of-the-extension-)
