### ISSUE TITLE
Enable Azure ML - Remote extension in workspace to support Remote in Remote Connection

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#2056]
After doing some preliminary testing, it seems to work by simply tweaking the extensionKind to ["workspace", "ui"] in package.json. If there are no side effects, we can enable it.

**Comment by sevillal** [comment]
That configuration was not recommended by VS Code since it might create issues with the remote experience. 

I think an easy way to mitigate this would be to disable the "Connect" (in same window) when from inside other remote connections and change the behavior of the "Connect in new window" in other remote connections context by open a remote connection URI with the `windowId=_blank` query parameter. We can create a new uriHandler path to keep identify connections coming from other remotes.
