### ISSUE TITLE
Submitting a script in a subdirectory of the opened folder, uses questionable aml_config folder...

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-tools-for-ai#230]
Open Folder1 that contains Folder2.
Folder2 contains the python script to run.
Create an experiment compute and runconfig
Specify to execute the python script as an experiment.

On submission, if there is an aml_config folder in Folder2, IT will be used rather than the one that's in Folder1 (which should contain the runconfig created above).

**Comment by shsuman** [comment]
The Azure sdk throws an error saying that the python script should be in the same folder as the project folder. So, this ultimately means by design if you have opened folder 1, the script should be in folder 1

**Comment by adyada** [comment]
If Folder2 also has aml_config then that will be used. I don't think azureml-sdk can do much here, a user might have aml_config in ~ folder, and there could be one in ~/Folder1 also. So, if you are in ~/Folder1 then azureml-sdk will use ~/Folder1/aml_config rather than ~/aml_config. 

If folder structure is ~/Folder1/Folder2/myscript.py , then from ~/Folder1 a user can definitely do run submit for Folder2/myscript.py . If a user is in ~/Folder1/Folder2/ and then run submit myscript.py then that may also work based on configs in  ~/Folder1/aml_config . But, this is a tricky case.
