### ISSUE TITLE
Not able to run azure compute in vscode web

### ISSUE THREAD

**Issue by ghhzshivam** [microsoft/vscode-tools-for-ai#2343]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Failed to authenticate.
Error type: AuthError

Version: 0.48.0
Browser Name: Chrome
Browser Version: 122.0.0.0
OS: Linux 64-bit
Product: Visual Studio Code
Product Version: 1.88.0
Language: en

<details>
<summary>Call Stack</summary>

```
kt.getSession webOpener.js:2:706485
https:/webOpener.js:2:785853
Ar.measure webOpener.js:2:792927
Tr.getSession webOpener.js:2:785811
Tr.create webOpener.js:2:785519
$n.resolve webOpener.js:2:742087
https:/webOpener.js:2:772433
Ar.measure webOpener.js:2:792927
Lr.doRoute webOpener.js:2:772390
Module.Ir webOpener.js:2:793530
```

</details>

**Comment by shsuman** [comment]
@sevillal Please take a look at this.

**Comment by sevillal** [comment]
@ghhzshivam thanks for filing this. This is a known issue that we are actively working with VS Code to get fixed, I will post next steps later this week. For reference this is the [upstream VS Code issue](https://github.com/microsoft/vscode/issues/197389).

**Comment by sevillal** [comment]
Hi @ghhzshivam, VS Code has implemented a solution to this issue, as of now we are testing it, could you please try it and report if your issue is resolved:

1. Go to Azure ML Studio and open the `Compute` tab
2. Right click on the `VS Code (Web)` link of your compute instance and click `Copy link`
3. Open a new browser tab
4. Paste the link and add `&useMsal=true` at the end of the URL
5. Type enter
6. Enter your credentials if needed and report if you are able to connect or if you see a different error
