### ISSUE TITLE
Failed to authenticate

### ISSUE THREAD

**Issue by farhana786** [microsoft/vscode-tools-for-ai#2368]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Failed to authenticate.
Error type: AuthError

Version: 0.48.0
Browser Name: Chrome
Browser Version: 124.0.0.0
OS: Windows 10 64-bit
Product: Visual Studio Code
Product Version: 1.89.1
Language: en

<details>
<summary>Call Stack</summary>

```
kt.getSession webOpener.js:2:706485
https:/webOpener.js:2:785853
Ar.measure webOpener.js:2:792927
Tr.getSession webOpener.js:2:785811
Tr.create webOpener.js:2:785519
$n.resolve webOpener.js:2:742087
https:/webOpener.js:2:772433
Ar.measure webOpener.js:2:792927
Lr.doRoute webOpener.js:2:772390
Module.Ir webOpener.js:2:793530
```

</details>

**Comment by farhana786** [comment]
![Azure AI- Failed to connect](https://github.com/microsoft/vscode-tools-for-ai/assets/13232448/458846b2-d725-4b2f-8bd3-59f8fa1bd172)

**Comment by shsuman** [comment]
@sevillal Can you please take a look into this ?

**Comment by sevillal** [comment]
Hi @farhana786 , VS Code has implemented a solution to this issue, as of now we are testing it, could you please try it and report if your issue is resolved:

1. Go to Azure ML Studio and open the `Compute` tab
2. Right click on the `VS Code (Web)` link of your compute instance and click `Copy link`
3. Open a new browser tab
4. Paste the link and add `&useMsal=true` at the end of the URL
5. Hit enter
6. Enter your credentials if needed and report if you are able to connect or if you see a different error

**Comment by sevillal** [comment]
Hi @farhana786 , we just rolled out a fix for this issue, could you please retry? Please reopen this issue if you face any problem.
