### ISSUE TITLE
Can not connect the VS code with AML

### ISSUE THREAD

**Issue by Birdy647JH** [microsoft/vscode-tools-for-ai#2383]
Does this occur consistently%3F 
Repro steps:

1.
2.

Error message: Failed to authenticate.
Error type: AuthError

Version: 0.48.0
Browser Name: Safari
Browser Version: 16.6
OS: OS X 10.15.7
Product: Visual Studio Code
Product Version: 1.89.1
Language: en

<details>
<summary>Call Stack</summary>

```
webOpener.js:2:704318
webOpener.js:2:704676
webOpener.js:2:706491
webOpener.js:2:707988
webOpener.js:2:785899
webOpener.js:2:792928
webOpener.js:2:793006
webOpener.js:2:785818
webOpener.js:2:785981
webOpener.js:2:785529
webOpener.js:2:785648
webOpener.js:2:742093
webOpener.js:2:742813
webOpener.js:2:772443
webOpener.js:2:792928
webOpener.js:2:793006
webOpener.js:2:772397
webOpener.js:2:774678
webOpener.js:2:793537
webOpener.js:2:793544
```

</details>

**Comment by shsuman** [comment]
@sevillal Please look into this :)

**Comment by sevillal** [comment]
@Birdy647JH  thanks for filing this. This is a known issue that we are actively working with VS Code to get fixed, I will post next steps later this week. For reference this is the https://github.com/microsoft/vscode/issues/197389

**Comment by sevillal** [comment]
Hi @Birdy647JH , VS Code has implemented a solution to this issue, as of now we are testing it, could you please try it and report if your issue is resolved:

1. Go to Azure ML Studio and open the `Compute` tab
2. Right click on the `VS Code (Web)` link of your compute instance and click `Copy link`
3. Open a new browser tab
4. Paste the link and add `&useMsal=true` at the end of the URL
5. Hit enter
6. Enter your credentials if needed and report if you are able to connect or if you see a different error

**Comment by sevillal** [comment]
Hi @Birdy647JH , we just rolled out a fix for this issue, could you please retry? Please reopen this issue if you face any problem.
