### ISSUE TITLE
Approximate prices added to computes based on duration within golden path

### ISSUE THREAD

**Issue by akashraju4** [microsoft/vscode-tools-for-ai#273]

**Comment by greazer** [comment]
From Nishank Gupta
Sorry that I am responding to this thread late, I was trying to get details for the cost estimate API on a parallel thread – see attached

Now the good news, there is an API that is used specifically to power the cost estimate in the screenshot below. It is used in the VM picker on the Azure portal, and @Sriram Kakara is investigating how to integrate into Workspace 2.0 for AzureML. I would recommend using the same API in the extension experience also. Comments:

It is an approximate cost, but does take into consideration offer types, so will differentiate between EA and PAYG subs for instance
It seems to be a more detailed API than the basic rate card API that we have in Azure
The API that you call today for listing VM sizes is something specific to AzureMLCompute – since we support a subset of VM sizes. Most likely you will have to call these two APIs individually and then correlate based on VM size. @Pradeep Kumar Gunda do you think its technically feasible to call this cost estimate API in our backend and surface the cost info as part of the listvmsizes API from our side? How expensive is this work?
As it stands, cost information is one of the single most pieces of usability feedback we have gotten from AzureML customers. This work will help us address AmlCompute, Data Science Instance, and the extension users.

Cc Swapnil for viz

**Comment by greazer** [comment]
The API provided to us does not have much details for the usage. There are terms that neither me nor the AML team understands. Awaiting on a meeting with Seung and Kalpana to get a better understanding of this

**Comment by SiddhanthUnnithan** [comment]
Follow up with Nishank about progress on API usage
