### ISSUE TITLE
Submit job problems on macOS

### ISSUE THREAD

**Issue by 00yk** [Microsoft/vscode-tools-for-ai#38]
Hi, I'm using VScode on macOS. 

When I submit the job(AI: Submit Job), it comes out the error message: "The terminal process command '/bin/zsh ~/.vscode/extensions/ms-toolsai.vscode-ai-0.1.9/out/scripts/pythonTerminal.sh' failed to launch (exit code: 127)."

And when I type the above command("/bin/zsh ~/.vscode/extensions/ms-toolsai.vscode-ai-0.1.9/out/scripts/pythonTerminal.sh") in the terminal, it showed me "pythonTerminal.sh" did not handle directory paths with spaces correctly.

Like, "/Applications/VMware Fusion.app/Contents/Public"  seems to miss a backslash 
---- "/VMware\ Fusion.app/".

**Comment by suntobright** [comment]
Thanks for your feedback.

This bug would be fixed in the next release.

By the meantime, you may
1) create a symbolic link to the python interpreter, the link path should not contain any space,
2) add the link as a new local configuration,
3) and use the new local configuration to submit job

to bypass this problem.

Sorry for the inconvenience.

**Comment by 00yk** [comment]
Thank you for the response. I've bypassed this problem by removing the path that contain spaces.
