### ISSUE TITLE
Function tests are not being run on Ubuntu Test Machine

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#401]
![image.png](https://images.zenhubusercontent.com/5c1828cfc50615756d6b3d5a/2450bc3b-221c-438d-9492-8dbc2f665992)

**Comment by sevillal** [comment]
Fixed with recommendation in: https://github.com/microsoft/vscode/issues/89147

Adding parameter **-screen 0 1024x768x24** when initializing xvfb.

**Pipeline**: https://msasg.visualstudio.com/OpenMind%20Studio/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=4351

**Step**: Set up Xvbf and clean up
