### ISSUE TITLE
Jupyter cannot preview

### ISSUE THREAD

**Issue by duzhen** [Microsoft/vscode-tools-for-ai#44]
with vscode, show following error:
Initialize log file failed: Path must be a string. Received undefined

Ubuntu 18.04 LTS
VSCode: 1.26.1

**Comment by linmajia** [comment]
@duzhen , thank you very much for the feedback.

VS Code Tools for AI does not officially support Linux yet, so there may be potential bugs. The root cause of this issue is that the logger is not initialized correctly on Linux. I think you could bypass it and continue your work, but such logger error messages may still pop up later.

We will fix the problem soon and welcome to tell us any issues you find on Linux.

Thanks.

**Comment by duzhen** [comment]
@linmajia, thanks for your response
is the AI plugin an open source project?
can I do something just make the Jupyter preview work.

**Comment by linmajia** [comment]
@duzhen , VS Code Tools for AI is not an open source project yet.

**Comment by AceHack** [comment]
I a having same issue, when will it be fixed?
