### ISSUE TITLE
How to specify jupyter path?

### ISSUE THREAD

**Issue by gennaro-tedesco** [Microsoft/vscode-tools-for-ai#46]
I have Jupyter installed on my computer (macOs Sierra 10.12.6) and I would like to specify the location path to the extention, in order to be able to run the notebooks.

When I right-click `AI: view in Jupyter Server`, I get the error `error: Jupyter is not installed in the current python path: /usr/local/bin/python3, please install jupyter first.`, which clearly shows that VSCode is not looking into the right path to start it: how can I custom-specify the Jupyter path?

**Comment by linmajia** [comment]
@gennaro-tedesco , thank you very much for the feedback.

VS Code Tools for AI relies on the "jupyter-notebook" binary to view Jupyter Notebooks. However, due to the installation diversity of Python distribution and wheel packages, we assume that "jupyter-notebook" is installed in the same folder with your Python interpreter on macOS. We will add Jupyter path configuration in the future update.

Currently, there are two workarounds:
1. Create a symbolic link of "jupyter-notebook" in the "/usr/local/bin" folder using "ln -s" command in a terminal.
![image](https://user-images.githubusercontent.com/9329359/44694877-b309fc00-aaa2-11e8-9f87-6dc600ae52da.png)

2. If "/usr/local/bin/python3" is just a symbolic link of e.g. "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3" and there is a "jupyter-notebook" in the same folder, run VS Code's command "Python: Select Interpreter" and change to the target Python.
![image](https://user-images.githubusercontent.com/9329359/44694936-17c55680-aaa3-11e8-9d30-34a389460ebb.png)

Thanks.

**Comment by gennaro-tedesco** [comment]
Thank you, the workaround works just fine.

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning. The Python Extension for VSCode now supports the ability to import, modify, and export jupyter notebooks.
