### ISSUE TITLE
a bug about ubuntu 16 vscode tools for ai

### ISSUE THREAD

**Issue by ErenTuring** [Microsoft/vscode-tools-for-ai#51]
I first used this nice extension in Window,  it work well. So I installed it in my Ubuntu environment. Unfortunately, there was a problem after the installation:
    Initialize log file failed: Path must be a string. Received undefined
And if I ignore the prompt to use, such as open a jupyter notebook by this extension, it will prompt such an error:
     Logger failed : Cannot read property 'log' of undefined
Hope to get answers, thanks!

**Comment by linmajia** [comment]
@ErenTuring , thank you very much for the feedback.

VS Code Tools for AI does not officially support Linux yet, so there may be potential bugs. The root cause of this issue is that the logger is not initialized correctly on Linux. We will fix the problem soon and welcome to tell us any issues you find on Linux.

Thanks.

**Comment by rbavery** [comment]
I also get the same error. I'm on ubuntu 16.04 and the same error appears after installing the latest version of VS Code and the ai tool.

**Comment by greazer** [comment]
Ubuntu is now supported on the 0.4.0 release. Please let us know if you run into further issues.
