### ISSUE TITLE
Users can't upload local files to the workspacefilestore datastore when creating a dataset.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#542]
When creating a Tabular or File dataset using local files the user is only shown the following options:

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/19cc37d7-2f49-4490-8624-b3b6a6a48054)

I.e. datastores they've created and the default workspace blob store.

Users should be allowed to upload their files to the default workspace file share as well:

![image.png](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/38d86003-8bd1-4696-8a5c-b5ed0970e457)

**Comment by tbombach** [comment]
We can probably support this with the azure file SDK (https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/storage-file-share/samples/javascript/basic.js), similar to how we use the azure blob SDK. Note that the portal doesn't support this right now - let's make sure to investigate this a bit to make sure we have the right experience. For blob upload, we followed the portal's example of having a {prefix}/{timestamp} folder prefix to allow users to create datasets that have versions. Blob storage makes this easy, since there are no actual folders for blobs, just virtual folders based on the path. For file shares, we need to parse the folder path that the user would specify and create the folder structure ourselves before uploading the local file

**Comment by tbombach** [comment]
Assigning to Sid to follow up with May about why the portal doesn't allow uploads to file shares

**Comment by SiddhanthUnnithan** [comment]
Spoke to May and team about it. They currently don't support file uploads - its on their backlog. We can investigate this once they've completed the work.

**Comment by SiddhanthUnnithan** [comment]
Closing in favour of 2.0 work where this functionality will be handled by the CLI.
