### ISSUE TITLE
Install as admin doesn't work on Linux

### ISSUE THREAD

**Issue by krzysdz** [Microsoft/vscode-tools-for-ai#56]
When I click `click here to run the script` and Run as Administrator is selected VS Code executes command:
```
undefined "/usr/bin/python3" install.py
```
Which *obviously* throws an error `undefined: command not found`

The extensions executes:
```javascript
// pythonPath is path to python configured in settings
// in extension code this variable is called t
this.terminal.sendText(`${j[l.platform()]} "${pythonPath}" install.py`)
```
to get the command to run and `j[l.platform()]` returns `undefined`.
`j` looks like this:
```javascript
j = {
    win32: ".\\runAsAdmin.cmd",
    darwin: "sudo"
};
```
so if `l.platform()` returns something other than `win32` or `darwin` - eg. `linux` the command is prefixed with `undefined` instead of `sudo`

**Comment by krzysdz** [comment]
Workaround:
```bash
# cd to extension directory
cd ~/.vscode/extensions/ms-toolsai.vscode-ai-0.2.0/scripts/local/
# run install script with sudo
sudo python3 install.py
```

**Comment by linmajia** [comment]
@krzysdz , thank you very much for the feedback.

VS Code Tools for AI does not officially support Linux yet, so there may be potential bugs. The root cause of this issue is that the logger is not initialized correctly on Linux. We will fix the problem soon and welcome to tell us any issues you find on Linux.

The installer to setup deep learning development is maintained on https://github.com/Microsoft/samples-for-ai . You can refer [here](https://github.com/Microsoft/samples-for-ai#using-a-one-click-installer-to-setup-deep-learning-frameworks) for installation.

Thanks.
