### ISSUE TITLE
Logger failed : Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by topwebmaster** [Microsoft/vscode-tools-for-ai#62]
When open ipynb file "View in Jupyter Server" got this error "Logger failed : Cannot read property 'log' of undefined"
OS: Linux Mint 19
python: system-3.6.5

**Comment by linmajia** [comment]
@topwebmaster , thank you very much for the feedback.

VS Code Tools for AI does not officially support Linux yet, so there may be potential bugs. The root cause of this issue is that the logger is not initialized correctly on Linux. We will fix the problem soon and welcome to tell us any issues you find on Linux.

Thanks.

**Comment by linmajia** [comment]
Duplicate #44

**Comment by AceHack** [comment]
Yes, any update?

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning. The Python Extension for VSCode now supports the ability to import, modify, and export jupyter notebooks and is actively being developed. Please try it out and log issues on the Python extensions issues list.
