### ISSUE TITLE
AI Tools not recognizing Jupyter install

### ISSUE THREAD

**Issue by Brgraul** [Microsoft/vscode-tools-for-ai#73]
After clicking _AI: View in Jupyter Server_, the system is not able to open the server, throwing the following console log:
```
Jupyter is not installed in the current python path: venv/bin/python, please install jupyter first.
```
I have correctly installed Jupyter, and it is possible to find the folder in the directory:  venv/bin/python/jupyter-notebook

**Comment by parthspatel** [comment]
I have a similar error, not using a venv.
```
Jupyter is not installed in the current python path: C:\Program Files (x86)\Python37-32, please install jupyter first.
```

**Comment by linmajia** [comment]
@Brgraul and @parthspatel , thank you very much for the feedback.

VS Code Tools for AI relies on the "jupyter-notebook" binary to view Jupyter Notebooks. However, due to the installation diversity of Python distribution and wheel packages, we assume:
1. On Windows,  the "jupyter-notebook.exe" is installed in the "Scripts" subfolder of your Python interpreter.
2. On macOS, "jupyter-notebook" is installed in the same folder with your Python interpreter.

We will add Jupyter path configuration in the future update. Please firstly set the Python interpreter in VS Code correctly and refer to a similar issue https://github.com/Microsoft/vscode-tools-for-ai/issues/46. Here are some workarounds
1. Copy "jupyter-notebook" binaries to the corresponding folder.
2. Make symbolic links of "jupyter-notebook" binaries in the corresponding folder."jupyter-notebook" binaries to the corresponding folder.
3. Switch to Python distribution from www.python.org instead of Anaconda.

BTW: @parthspatel , you need to install 64-bit Python 3.5 or 3.6 to use deep learning frameworks such as TensorFlow, CNTK etc.

**Comment by greazer** [comment]
This extension has been redesigned to target scenarios only dealing with Azure Machine Learning. The Python Extension for VSCode now supports the ability to import, modify, and export jupyter notebooks and is actively being developed. Please try it out and log issues on the Python extensions issues list.
