### ISSUE TITLE
Workspace selection in quick-pick is unresponsive [remote server flow]

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#769]
![azml-extension.gif](https://images.zenhubusercontent.com/5dd6ec14b026170001c5096b/45b5e101-29a8-4925-9564-2e1cc78d3ecb)

From @dkmiller. Followed up to see if there anything is being outputted to the "Outputs" pane. If nothing in Outputs we can try toggling more logging.

**Comment by dkmiller** [comment]
@SiddhanthUnnithan good suggestion to look at the "Outputs" pane. It turns out the "doing nothing" was just VS Code looking for compute instances in the workspace.

The latency is pretty bad though. If you see the GIF below, it takes 10&ndash;15 seconds to get from selecting the `aml1p-ml-wus2` workspace to selecting my compute instance. The initial selection of the CI is unsuccessful as well &mdash; I have to reselect it to get it to work.

![azml-extension-success](https://user-images.githubusercontent.com/5003801/97456431-1a779c80-18f6-11eb-81a9-72f60d0aec11.gif)

**Comment by SiddhanthUnnithan** [comment]
@dkmiller thanks for pointing the latency issue out. I'll follow up with the dev team to see if we can work with you to run a performance profiler to see where the perf issue is.

Regarding the unsuccessful first attempt - that unfortunately has to do with the "signals" that the Python extension is looking for. After you select the compute instance the first time and reload the window, you **must** run a cell in order for the connection to happen. Overall the reload+run cell experience is undesirable and we're working on improving it for the new Native Notebook experience.

**Comment by dkmiller** [comment]
@SiddhanthUnnithan thanks for clarifying. Is there any way we can make a visual indication inside the dropdown that "something" is happening when the user clicks e.g. on a workspace?

**Comment by SiddhanthUnnithan** [comment]
Good suggestion @dkmiller! We're hoping to investigate the following:
1. Show progress in the quick-pick itself.

Also follow up with Design team to see if there're alternative visual indication options.

**Comment by SiddhanthUnnithan** [comment]
@sevillal assigning this to you so that we can tie it to your ongoing transaction. Let's try and get this in 0.6.22?

**Comment by SiddhanthUnnithan** [comment]
@sevillal do you think it makes sense to include this for 0.6.24? Should we push it out to 0.6.25? Will this still be relevant with the refactoring work?

**Comment by sevillal** [comment]
This should be solved with refactor work, will assign it to the right epic part of the GA.

**Comment by shsuman** [comment]
Already implemented with new selection services
