### ISSUE TITLE
Investigate why the remote window is unable to interact with a local browser

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-tools-for-ai#815]
Confirmed that this works in other remote extensions (Remote-SSH).

Need to investigate why the AML remote window is unable to connect to the local browser.

Test with the "Azure Account: Sign In" command.

**Comment by shsuman** [comment]
"Azure: Sign in" doesn't work in remote window. This maybe because they use some kind of local server to sign in which obviously won't work in a remote setup. All the other browser interactions are working fine. However, the Azure: Sign in is working with the remote window, I am guessing because of some port forwarding or so.

**Comment by shsuman** [comment]
I think all interactions with browser works now, so we can close this
