### ISSUE TITLE
Support $schema property

### ISSUE THREAD

**Issue by sevillal** [microsoft/vscode-tools-for-ai#925]
Support $schema property and enable dynamic schema registration for the files containing it.

**Comment by SiddhanthUnnithan** [comment]
- First we need to support the $schema property
- What do we need to do to support this tag?
- What is the best approach => start from scratch, build on top of what the RH team has already done, what happens after they add the support.

- Start with commenting on their issue and ask about progress / merge plans.
- Otherwise consider forking and publishing our own package.

**Comment by shsuman** [comment]
Following up with the RedHat team to know if they are gonna merge the PR.

https://github.com/redhat-developer/yaml-language-server/pull/354

**Comment by shsuman** [comment]
Merged PR: https://msasg.visualstudio.com/OpenMind%20Studio/_git/OpenMindVSCode/pullrequest/2083544

and tracking conversation with RedHat in #957
