### ISSUE TITLE
Move our websocket server bits from github to MSDN

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode-tools-for-ai#953]

**Comment by SiddhanthUnnithan** [comment]
The guidance provided here was to look into bundling the websocket server with our remote extension so that we can use that as a failsafe (or all the time) if we're unable to get the bits from the public internet.

One concern that was brought up was the current size of the websocket server is 15MB and this would significantly increase the size of our extensions.

**Comment by SiddhanthUnnithan** [comment]
After further discussion we think we can overcome the extension size issue by bundling the websocket server with the Remote extension as opposed to the main one. We are not keen to go down the route of trying to use node that comes with VS Code server because of potential version mismatches / incompatibility.

**Comment by SiddhanthUnnithan** [comment]
GA requirement - partial support for "air-gapped" customers that have access to a limited number of public endpoints.

**Comment by SiddhanthUnnithan** [comment]
De-prioritizing. We've been asking users to approve the github endpoints and haven't gotten any  complaints so far.
