### ISSUE TITLE
Cannot connect or work with Jupyter notebooks in VSCode

### ISSUE THREAD

**Issue by lafranke** [microsoft/vscode-tools-for-ai#979]
## Expected Behavior
Can run Jupyer notebooks and be able to open them in VSCode.

## Actual Behavior
Two different scenarios:
1. I managed to open my repository in VSCode, but I could not run the code. 
2. I cannot open/connect to AML over VSCode after clicking on "VSCode" in the AML Studio. 

## Steps to Reproduce the Problem
To problem numer 1:
1. go into AML Studio
2. go to compute instances
3. click on VS Code
4. VS Code opens and displays my notebooks
5. When opening an existing one or creating a new one I get this error message: EINVAL: invalid argument, scandir '/mnt/batch/tasks/shared/LS_root/mounts/clusters/my-cpu-ds11/code/C:\Users\lfranke\Anaconda3/share/jupyter/kernels'. However, working with the Jupyter notebooks works when choosing "Jupyter" in step 3

To problem 2:
1. Work a bit with the notebooks online, i.e. in the Jupyter View
2. Go back to compute instance in the AML Studio
3. Click on VS Code
4. VS Code opens however does not dispaly anything and says: "Failed to connect to the remote extension host server (Error: Decryption failed)" and "Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed or enabled."

## Specifications

  - Version: VSCode: 1.55.1
  - Platform: Windows 10

**Comment by SiddhanthUnnithan** [comment]
Hi @lafranke,

Do you mind specifying which version of the "Azure Machine Learning" and "Azure Machine Learning - Remote" extensions you're using.

We believe that the first problem is related to the Jupyter extension installed on the compute instance. We will be working with the Jupyter extension team to help resolve this issue.

Re: the second problem - do you mind letting me know if you were able to use the remote connection feature prior to March 30th (and thus were using VS Code 1.54)? We believe this may be due to a known secrets issue that arose between 1.54 and 1.55. Here is a relevant issue: https://github.com/microsoft/vscode/issues/120558

We are working on resolving this issue in our extension and will get back to you immediately once we've found a mitigation.

**Comment by lafranke** [comment]
Hi there,

So I tried to connect to the Compute Instance over VS Code, and it load successfully. I then ran an "import azureml..core" command and it requested to install another Jupyter version (Downloading jupyter-1.0.0-py2.py3-none-any.whl) - I assume on Azure ML - and then successfully ran the above command and also loaded my Workspace.

However, calling VSCode over the AML portal still does not work.

Cheers,
Laura
